### ISSUE TITLE
Warden Auth

### ISSUE THREAD

**Issue by captainmangoC4** [code-423n4/code423n4.com#1431]
- [x] implement client-side auth with Moralis
- [x] style user dropdown
- [x] implement team registration
- [x] allow merging addresses in moralis
- [x] verify user when they submit a finding while logged in
- [x] verify teams when a member submits a finding @captainmangoC4 
- [x] change UI in submission form to allow wardens who are on teams to toggle between submitting as an individual or as their team @captainmangoC4 
- [x] add a [+ email address] button to create multiple email fields for team submissions @captainmangoC4 
- [x] #2068
- [x] verify users when they register @captainmangoC4 
- [x] save polygon address for a team upon first submission @captainmangoC4 
- [x] create confirmation modal  @Simon-Busch 
- [x] use confirmation modal for confirming team polygon address and for merging addresses in moralis @captainmangoC4 
- [X] validate discord username @Simon-Busch 
- [x] protect finding submission page @captainmangoC4 
- [x] restyle submission form @captainmangoC4 
- [ ] create staging environment @joshuashort @captainmangoC4 
- [x] clean up finding submission form logic @captainmangoC4 
- [x] set up production database @captainmangoC4 
- [ ] finalize messaging @captainmangoC4 @tealtigrrr 
- [x] https://github.com/code-423n4/code423n4.com/issues/2046 -- style message for user to login for registration page and submit finding page
- [x] #2091
- [x] #2096
- [x] filter options in warden dropdown, removing wardens who have previously submitted findings?
- [x] clean up addresses from previous submissions table

**Comment by captainmangoC4** [comment]
For the pages that require auth (submit findings and register team), if the user is not logged in, show a message telling them to login. Message should be styled to look like the submit finding success message.

For submit findings, it should say something like:

## Please log in
You need to be a registered warden currently connected via wallet to see this page.

**Note to existing wardens:**
As of [date] wardens are required to authenticate with a wallet to submit findings.

You can read more about this change here[link].

[connect with MetaMask] [connect with WalletConnect]



For team registration page, it should say:

## Please log in
You need to be a registered warden, currently connected via wallet to register a team.

[connect with MetaMask] [connect with WalletConnect]

**Comment by Simon-Busch** [comment]
> For the pages that require auth (submit findings and register team), if the user is not logged in, show a message telling them to login. Message should be styled to look like the submit finding success message.
> 
> For submit findings, it should say something like:
> 
> ## Please log in
> You need to be a registered warden currently connected via wallet to see this page.
> 
> **Note to existing wardens:** As of [date] wardens are required to authenticate with a wallet to submit findings.
> 
> You can read more about this change here[link].
> 
> [connect with MetaMask] [connect with WalletConnect]
> 
> For team registration page, it should say:
> 
> ## Please log in
> You need to be a registered warden, currently connected via wallet to register a team.
> 
> [connect with MetaMask] [connect with WalletConnect]

Done in issue https://github.com/code-423n4/code423n4.com/issues/2046 :-) 

Waiting for your review

**Comment by sockdrawermoney** [comment]
I suggest considering #2100 as part of this effort in order to clean up repo activity and better manage permissions.

git submodules are pretty easy to implement if you're not familiar, and I'm happy to help.

**Comment by Simon-Busch** [comment]
> I suggest considering #2100 as part of this effort in order to clean up repo activity and better manage permissions.
> 
> git submodules are pretty easy to implement if you're not familiar, and I'm happy to help.

I am not familiar with it, I definitely want to do it 👍🏼

**Comment by tealtigrrr** [comment]
> I suggest considering #2100 as part of this effort in order to clean up repo activity and better manage permissions.
> 
> git submodules are pretty easy to implement if you're not familiar, and I'm happy to help.

Hey @sockdrawermoney we discussed this in our sync and agreed that while it would be good to use the submodule solution in the future, it adds a little too much complexity to implement it _before_ we launch v1 of Warden Auth (since we are eager to get it out the door).

We are thinking that we can tackle this as part of our first post-launch set of fixes/enhancements for the auth/registration process.

Since the vast majority of registrations in the first few weeks will likely be re-registrations, I think we'll be able to avoid some of the awkward situations this approach solves for.

@sockdrawermoney You ok with us pushing this (#2100) until after launch?
