### ISSUE TITLE
Fetch discord UserID on warden registration

### ISSUE THREAD

**Issue by Simon-Busch** [code-423n4/code423n4.com#2319]
Actions:

- [ ] Install discord JS
- [ ] In `register-warden` fetch userId from their username
- [ ] Update Moralis to accept to store this extra data

**Comment by Simon-Busch** [comment]
As per discussion with @captainmangoC4  we decided not to store this information.
