### ISSUE TITLE
Fall 21 Site Update

### ISSUE THREAD

**Issue by tealtigrrr** [code-423n4/code423n4.com#365]
**Site Updates**
- [x] logo added to site @DianaPerkinsDesign 
- [x] hero copy change (https://github.com/code-423n4/code423n4.com/issues/341) @DianaPerkinsDesign 
- [x] contest pages ([#48](https://github.com/code-423n4/code423n4.com/issues/48)) @DianaPerkinsDesign 
- [x] Update favicon
- [x] update any references to twitter handle??

**DNS/Netlify/redirects**
- [ ] Netlify C4 website config making code4rena.com the main site
- [ ] Netlify DNS config making code423n4.com point to redirect repo
- [ ] Netlify redirects app config point to code4rena.com/* instead

**Twitter**
- [ ] announcement tweet 
- [x] new avatar designed @tealtigrrr 
- [x] new header art designed 
- [x] new images uploaded @CloudEllie 
- [x] name/handle updated 

**Other sites/tools**
- [ ] Update Discord avatar/name/links @CloudEllie @itsmetechjay 
- [x] Update Discourse avatar/name/links
- [ ] Update Gitbook docs avatar/name/links @CloudEllie @itsmetechjay 
- [x] Update GitHub avatar/name/links

_**Moving to a later release:**_
- [ ] routing emails? @ninek9 
- [ ] get an audit page  page ([#342](https://github.com/code-423n4/code423n4.com/issues/342))
- [ ] compete page ([#343](https://github.com/code-423n4/code423n4.com/issues/343))
- [ ] minor ux style updates (if time allows)

**Comment by CloudEllie** [comment]
Signed up me & @itsmetechjay to manage the Discord and GitBook updates

**Comment by CloudEllie** [comment]
Re: the compete page, there's an old one here that still appears in Google results -- https://code423n4.com/compete/ -- so might be good to simply retool it in case it has any value from an SEO perspective.

**Comment by CloudEllie** [comment]
Similarly, there's a "Sponsoring a contest" page still visible via Google results: https://code423n4.com/sponsor/

**Comment by ninek9** [comment]
we can do the emails whenever, agree that's not a blocker for this launch.

**Comment by DianaPerkinsDesign** [comment]
I don't know that this is relevant anymore. Closing; Feel free to reopen if needed!
